# Generated by Django 4.2.7 on 2023-11-10 00:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agentes",
            fields=[
                (
                    "idgerente",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("nombreg", models.CharField(max_length=255)),
                ("telefenog", models.CharField(max_length=20)),
                ("usuariog", models.CharField(max_length=50, unique=True)),
                ("passwordg", models.CharField(max_length=100)),
                ("saldo", models.IntegerField()),
                ("edadg", models.IntegerField()),
                ("localidadg", models.CharField(max_length=100)),
            ],
        ),
    ]
