# Generated by Django 5.0 on 2023-12-28 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operadoras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operadoras',
            name='id',
        ),
        migrations.AlterField(
            model_name='operadoras',
            name='clave',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
