# Generated by Django 4.2.7 on 2023-12-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paquetes",
            fields=[
                (
                    "idpaquete",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("nombrep", models.CharField(max_length=150)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("urlimagen", models.CharField(max_length=255, unique=True)),
                (
                    "costopersona",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
            ],
        ),
    ]
