# Generated by Django 4.2.6 on 2023-11-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombrec', models.CharField(max_length=255)),
                ('telefenoc', models.CharField(max_length=20)),
                ('usuarioc', models.CharField(max_length=50, unique=True)),
                ('passwordc', models.CharField(max_length=100)),
                ('edadc', models.IntegerField()),
                ('localidad', models.CharField(max_length=100)),
            ],
        ),
    ]
