# Generated by Django 4.2.6 on 2023-11-10 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idprov', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('telefenoprov', models.CharField(max_length=20)),
                ('correoprov', models.CharField(max_length=50, unique=True)),
                ('nombreprov', models.CharField(max_length=255)),
            ],
        ),
    ]
