# Generated by Django 5.0 on 2024-01-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('papeleria', 'Papelería'), ('mensuales', 'Gastos Mensuales'), ('otros', 'Otros')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('recibo', models.ImageField(blank=True, null=True, upload_to='recibos/')),
            ],
        ),
    ]
