# Generated by Django 5.0 on 2023-12-29 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='venta',
            field=models.ForeignKey(default=1, help_text='Venta asociada al pago', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='reservas.venta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venta',
            name='saldo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Saldo de la venta', max_digits=10, null=True),
        ),
    ]
